manipulator:


  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.002
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 5
  position_only_ik: True

